### Get all Todos
GET http://localhost:3000/todo

### Create todo
POST http://localhost:3000/todo
Content-type: application/json

{
    "message": "sa4e todos"
}

### Register User
POST http://localhost:3000/auth/register
Content-type: application/json

{
    "name": "Joao",
    "email": "emaildx@gmail.com",
    "password": "password"
}

### Login
POST http://localhost:3000/auth/login
Content-type: application/json

{
    "email": "email@gmail.com",
    "password": "passfword"
}
