### Get all Tod@os
GET http://localhost:3000/todo

### Create todo
POST http://localhost:3000/todo
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9hbyIsImlhdCI6MTY3MDc5OTI0MiwiZXhwIjoxNjcwODAyODQyfQ.7ToYhdw-cUvK5kKx5H-XMo3EZ4pEq7DprMM-WVk-okI

{
    "message": "se4"
}

### Register User
POST http://localhost:3000/auth/register
Content-type: application/json

{
    "name": "Joao",
    "email": "email@gmail.com",
    "password": "password"
}

### Login
POST http://localhost:3000/auth/login
Content-type: application/json

{
    "email": "email@gmail.com",
    "password": "password"
}



### Test auth guard

POST http://localhost:3000/auth/test
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOGU0ZGUxNTcxNzJlMDAyYmE5MWFiMyIsIm5hbWUiOiJKb2FvIiwiaWF0IjoxNjcwMjcxNjAyLCJleHAiOjE2NzAyNzUyMDJ9.Ienko-3Hzsv7kd4StdWldMajVVUa1O0rntOYx6BcZBY

{
}