/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace auth {
    export interface AuthGrpcService {
        register(
            data: RegisterRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<RegisterResponse>;
        login(
            data: LoginRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<LoginResponse>;
        refreshToken(
            data: RefreshTokenRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<RefreshTokenResponse>;
        validateToken(
            data: ValidateTokenRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ValidateTokenResponse>;
    }
    export interface User {
        id?: string;
        name?: string;
        email?: string;
    }
    // Register
    export interface RegisterRequest {
        name?: string;
        email?: string;
        password?: string;
    }
    export interface RegisterResponse {
        accessToken?: string;
        refreshToken?: string;
    }
    // Login
    export interface LoginRequest {
        email?: string;
        password?: string;
    }
    export interface LoginResponse {
        accessToken?: string;
        refreshToken?: string;
    }
    // Refresh
    export interface RefreshTokenRequest {
        token?: string;
    }
    export interface RefreshTokenResponse {
        accessToken?: string;
        refreshToken?: string;
    }
    // Validate
    export interface ValidateTokenRequest {
        token?: string;
    }
    export interface ValidateTokenResponse {
        isValid?: boolean;
    }
}

