/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace todo {
    export interface TodoGrpcService {
        createTodo(
            data: CreateTodoRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<TodoResponse>;
        getAllTodo(
            data: NoParameters,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<TodoListResponse>;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface NoParameters {
    }
    export interface CreateTodoRequest {
        message?: string;
        userId?: string;
    }
    export interface TodoResponse {
        id?: string;
        userId?: string;
        message?: string;
        completed?: boolean;
    }
    export interface TodoListResponse {
        todos?: todo.TodoResponse[];
    }
}

