name: Artillery Smoke Test

on:
  push:
    branches:
      - main

jobs:
  artillery:
    runs-on: ubuntu-latest

    container: artilleryio/artillery:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run docker-compose
        run:
          - docker-compose --profile server up -d
          - docker-compose --profile app up -d

      - name: Start Infrastucture
        run: docker-compose --profile server up -d

      - name: Start Services
        run: docker-compose --profile app up -d

      - name: Make reports directory
        run: mkdir reports

      - name: Execute load tests
        run: /home/node/artillery/bin/artillery run --output reports/report.json tests/performance/todos.yml

      - name: Generate HTML report
        run: /home/node/artillery/bin/artillery report --output reports/report reports/report.json

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: artillery-test-report
          path: reports/*
